"use client";

import React, { useState, useEffect } from "react";
import { Search, X, Ship, Anchor, Navigation, FileText, ArrowRight } from "lucide-react";
import Link from "next/link";

interface SearchModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function GlobalSearchModal({ isOpen, onClose }: SearchModalProps) {
  const [query, setQuery] = useState("");

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "k" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        onClose();
      }
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [onClose]);

  if (!isOpen) return null;

  const mockResults = [
    { type: "Vessel", name: "MV Baltic Star", detail: "Supramax 57,000 DWT • Available", href: "/chartering" },
    { type: "Vessel", name: "MV Ocean Grace", detail: "Ultramax 64,000 DWT • Immediate", href: "/chartering" },
    { type: "Port", name: "Visakhapatnam (INVTZ)", detail: "East Coast India • 16.5m Draft", href: "/ports-routes" },
    { type: "Port", name: "Paradip (INPRT)", detail: "East Coast India • 16.0m Draft", href: "/ports-routes" },
    { type: "Route", name: "Singapore → Chennai", detail: "1,680 NM • 5.4 Days Transit", href: "/forecast" },
    { type: "Report", name: "Q2 2025 East Coast Freight Outlook", detail: "PDF • Generated by ML Engine", href: "/reports" }
  ];

  const filtered = query.trim()
    ? mockResults.filter(r => r.name.toLowerCase().includes(query.toLowerCase()) || r.detail.toLowerCase().includes(query.toLowerCase()))
    : mockResults;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-20 bg-slate-900/40 backdrop-blur-sm p-4">
      <div className="w-full max-w-2xl bg-white rounded-2xl shadow-2xl border border-sky-100 overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        <div className="flex items-center px-4 py-3.5 border-b border-slate-100 gap-3">
          <Search className="w-5 h-5 text-sky-600" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search vessels, ports, routes, reports... (e.g. Baltic Star, Chennai)"
            className="w-full text-slate-800 text-sm placeholder:text-slate-400 focus:outline-none"
            autoFocus
          />
          <button
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-3 max-h-96 overflow-y-auto divide-y divide-slate-50">
          {filtered.length === 0 ? (
            <div className="py-8 text-center text-slate-400 text-sm">
              No matching maritime assets found for "{query}".
            </div>
          ) : (
            filtered.map((item, idx) => (
              <Link
                key={idx}
                href={item.href}
                onClick={onClose}
                className="flex items-center justify-between p-3 rounded-xl hover:bg-sky-50/60 transition-colors group"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-lg bg-sky-100/70 text-sky-700 flex items-center justify-center shrink-0">
                    {item.type === "Vessel" && <Ship className="w-4 h-4" />}
                    {item.type === "Port" && <Anchor className="w-4 h-4" />}
                    {item.type === "Route" && <Navigation className="w-4 h-4" />}
                    {item.type === "Report" && <FileText className="w-4 h-4" />}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold text-slate-800 group-hover:text-sky-700 transition-colors">
                        {item.name}
                      </span>
                      <span className="text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.5 rounded bg-slate-100 text-slate-600">
                        {item.type}
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mt-0.5">{item.detail}</p>
                  </div>
                </div>
                <ArrowRight className="w-4 h-4 text-slate-300 group-hover:text-sky-600 group-hover:translate-x-0.5 transition-all" />
              </Link>
            ))
          )}
        </div>

        <div className="px-4 py-2.5 bg-slate-50 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400">
          <span>Search across 55 vessels, 22 ports & 54 shipping corridors</span>
          <span>ESC to close</span>
        </div>
      </div>
    </div>
  );
}
